---
- name: "Instalacion TMUX"
  apt:
    name: tmux
    state: present
  become: true
  become_method: sudo
- name: "Copiado de configuracion Tmux"
  copy:
    src: "{{ role_path }}/files/.tmux.conf"
    dest: "{{ ansible_env.HOME }}"
